#pragma once
#include "configurations.h"


// #define LEFT_FRONT_MOTOR_CONTROLLER_CAN_ID     1
// #define LEFT_CENTER_MOTOR_CONTROLLER_CAN_ID    2
// #define LEFT_REAR_MOTOR_CONTROLLER_CAN_ID      3

// #define RIGHT_FRONT_MOTOR_CONTROLLER_CAN_ID    4
// #define RIGHT_CENTER_MOTOR_CONTROLLER_CAN_ID   5
// #define RIGHT_REAR_MOTOR_CONTROLLER_CAN_ID     6

#define SINGLE_CONTROLLER_TEST_CAN_ID          1

#define POWER_DISTROBUTION_HUB                 6